export function isBang(type: any): any;
export function Bang(event: any, schema: any): any;
export function isInt(type: any): any;
export function Int(value: any, min: any, max: any, schema: any): any;
export function isFloat(type: any): any;
export function Float(value: any, min: any, max: any, schema: any): any;
export function isNum(type: any): any;
export function Num(value: any, min: any, max: any, schema: any): any;
export function isEnum(type: any): any;
export function Enum(value: any, enumOptions: any, schema: any): any;
export function isArr(type: any): any;
export function Arr(value: any, items: any, schema: any): any;
export function isObj(type: any): any;
export function Obj(properties: any, schema: any): any;
export function isStr(type: any): any;
export function Str(value: any, schema: any): any;
export function isBool(type: any): any;
export function Bool(value: any, schema: any): any;
export function isColor(type: any): any;
export function Color(value: any, schema: any): any;
export function isVec2(type: any): any;
export function Vec2(value: any, schema: any): any;
export function isVec3(type: any): any;
export function Vec3(value: any, schema: any): any;
export function isVec4(type: any): any;
export function Vec4(value: any, schema: any): any;
export const BUFF: "buffer";
export function isBuff(type: any): any;
export function Buff(value: any, schema: any): any;
export function isTex(type: any): any;
export function Tex(value: any, schema: any): any;
export function isAny(type: any): boolean;
export function Any(value: any, schema: any): any;
//# sourceMappingURL=_Types.d.ts.map